### ISSUE TITLE
API error message

### ISSUE THREAD

**Issue by dreamcat4** [sveniu/gtrans#1]
Hi,
Tried `gtrans.pl` for the first time today. From the official Irssi scripts repository.

Here is what it said:

```
$ apt-get update && apt-get install -y make cpanminus && cpanm WebService::Google::Language

$ irssi

/script load broken/gtrans.pl

09:48 GTrans loaded. Hints: /gtrans help
09:48  -!- Irssi: Loaded script gtrans

/gtrans --test fi:this is a small test

09:49 GTrans error> wgl_process() wgl_func() code 403: Please use Translate v2.  See http://code.google.com/apis/language/translate/overview.html
09:49 GTrans error> Translation failed with code 403: Please use Translate v2.  See http://code.google.com/apis/language/translate/overview.html
```

**Comment by sveniu** [comment]
Unfortunately, the free Google Translate API was discontinued in December 2011. The newer Translate v2 API is a paid service, and as my need for real-time IRC translation disappeared, I never signed up for it.

The gtrans plugin is probably ripe for removal from the Irssi scripts listings and packages, unfortunately; I don't foresee an effort to integrate it with the Translate v2 API, at least not from my side. Sorry.

**Comment by dreamcat4** [comment]
Yeah thanks. Sorry for not knowing. Just found out here:

http://wiki.znc.in/Translate

> Google chose to close its Translate API at 2011-12-01 and made it a paid service,
